name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Git Basics — Basic Check
      id: git-basics-basic-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Git Basics — Basic Check
        setup-command: ''
        command: test -f task.txt && [ $(git rev-list --count HEAD) -ge 3 ]
        timeout: 1
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GIT-BASICS-BASIC-CHECK_RESULTS: "${{steps.git-basics-basic-check.outputs.result}}"
      with:
        runners: git-basics-basic-check
